apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
data:
  MLFLOW_SERVE_ARTIFACTS: {{ .Values.artifacts.serve | quote }}
  MLFLOW_ARTIFACTS_DESTINATION: {{ .Values.artifacts.destination | quote }}
