apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  MLFLOW_BACKEND_STORE_URI: {{ .Values.backendStore.uri | b64enc | quote }}
  {{- if .Values.s3 }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.s3.endpoint | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.key | b64enc | quote }}
  {{- end }}
 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-artifact-credentials
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.artifacts.credentials.google }}
  credentials.json: {{ . | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-artifact-certificates
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.artifacts.certificates.s3 }}
  custom_certificate.cert.pem: {{ . | b64enc | quote }}
  {{- end }}