apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  MLFLOW_BACKEND_STORE_URI: {{ .Values.mlflow.backendStore.uri }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-artifact-credentials
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.mlflow.artifacts.credentials.google }}
  credentials.json: {{ . | b64enc | quote }}
  {{- end }}
